### ISSUE TITLE
I'm hungry, sandwich pls

### ISSUE THREAD

**Issue by Demozo** [ArcOfDream/VisioKnight#7]
Preferably a grilled cheese sandwich with ham or salami. Don't forget the ketchup and mayo!

Thanks 👍

**Comment by ArcOfDream** [comment]
Unfortunately we don't have ketchup, hope you accept pickles.

**Comment by ArcOfDream** [comment]
Almost forgot.

![Blurb](https://thumbs.dreamstime.com/z/wielka-kanapka-z-serem-1821365.jpg)

**Comment by Demozo** [comment]
Pickles are fine as well. 👎 for customer service, however.
